name:                html-parser
version:             0.1.0.0
github:              "Shenmin-Z/html-parser"
license:             BSD3
author:              "Shenmin Zhou"
maintainer:          "shenminzhou@gmail.com"
copyright:           "Shenmin Zhou"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Shenmin-Z/html-parser#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  html-parser-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - html-parser

tests:
  html-parser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - html-parser
